version: '2'

services:
  nginx:
      image: nginx:latest
      ports:
          - 8080:80
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
          - php
  php:
      build: ./docker/php/
      expose:
          - 9000
          - 8000
      ports:
        - 8000:8000
      volumes:
          - ./symfony/:/var/www/html/
